add a new line end of code
pysonDB/pysonDB pull request #72
Opened 2021-11-04 13:16 UTC by jakbin

2021-11-04 13:28 UTC, Adwaith-Rajesh requested changes

2021-11-04 13:32 UTC, jakbin commented on CHANGELOG.md
> +- `1.5.6`
then i change it into `1.5.7`

2021-11-04 13:34 UTC, Adwaith-Rajesh commented on CHANGELOG.md
> +- `1.5.6`
yeah

2021-11-05 06:22 UTC, jakbin commented
@Adwaith-Rajesh

2021-11-05 06:24 UTC, merged